server: # REST and WS server
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
      - dependency: "dev.lavalink.youtube:youtube-plugin:1.8.3"
        repository: "https://maven.lavalink.dev/releases"
  pluginsDir: "./plugins"
  server:
    password: "youshallnotpasswordtest"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      http: false
      local: false
    filters: # All filters are enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    nonAllocatingFrameBuffer: false  # 메모리 할당을 줄여 CPU 부하를 낮추면서 트래픽 안정성 확보.
    bufferDurationMs: 400  # GC 중단에 대한 내성을 유지하면서 트래픽 안정성을 위한 적절한 버퍼 크기.
    frameBufferDurationMs: 1000  # 너무 많은 오디오 데이터를 버퍼링하지 않도록 설정하여 트래픽을 일정하게 유지.
    opusEncodingQuality: 10  # 높은 품질로 CPU와 트래픽 균형을 유지.
    resamplingQuality: HIGH  # 높은 리샘플링 품질로 CPU 부하를 줄이면서 일정한 트래픽 흐름 유지.
    trackStuckThresholdMs: 10000  # 트랙이 멈춰 있는 시간을 약간 더 길게 잡아 일시적인 중단을 처리.
    useSeekGhosting: true  # 메모리 사용량 절감을 위해 비활성화.
    youtubePlaylistLoadLimit: 5  # 메모리 사용량을 고려해 유튜브 재생목록 로드를 5페이지로 제한.
    playerUpdateInterval: 5  # 플레이어 업데이트 빈도를 줄여 트래픽 부하를 일정하게 유지.
    youtubeSearchEnabled: true  # YouTube 검색 활성화.
    soundcloudSearchEnabled: true  # SoundCloud 검색 활성화.
    gc-warnings: true  # GC 경고를 활성화하여 트래픽 문제를 사전에 파악.


          #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
    #youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
      #email: "" # Email of Google account
      #password: "" # Password of Google account
    #httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
      #proxyHost: "localhost" # Hostname of the proxy, (ip or domain)
      #proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
      #proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
      #proxyPassword: "" # Password for basic authentication

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30

plugins:
  youtube:
      enabled: true # Whether this source can be used.
      allowSearch: true # Whether "ytsearch:" and "ytmsearch:" can be used.
      allowDirectVideoIds: true # Whether just video IDs can match. If false, only complete URLs will be loaded.
      allowDirectPlaylistIds: true # Whether just playlist IDs can match. If false, only complete URLs will be loaded.
      # The clients to use for track loading. See below for a list of valid clients.
      # Clients are queried in the order they are given (so the first client is queried first and so on...)
      clients:
        - MUSIC
        - TVHTML5EMBEDDED
        - ANDROID_MUSIC
        - ANDROID_TESTSUITE
        - WEB
        - WEBEMBEDDED
        - ANDROID
        - ANDROID_LITE
        - MEDIA_CONNECT
        - IOS

      # You can configure individual clients with the following.
      # Any options or clients left unspecified will use their default values
      # for those individual clients.
      # Client configurations will ONLY take effect if the client is registered above,
      # otherwise they are ignored.
      # ---------------- WARNING ----------------
      # This part of the config is for DEMONSTRATION PURPOSES ONLY!
      # Do NOT use this config before understanding what the options do.
      # You do NOT need to copy this config just because it is published here.
      # ---------------- WARNING ----------------
      WEB: # names are specified as they are written below under "Available Clients".
        # This will disable using the WEB client for video playback.
        playback: false
      TVHTML5EMBEDDED:
        # The below config disables everything except playback for this client.
        playlistLoading: false # Disables loading of playlists and mixes for this client.
        searching: false # Disables the ability to search for videos for this client.
