server: # REST and WS server
  port: 62363
  address: 0.0.0.0

lavalink:
  plugins:
      - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.1"
        repository: "https://maven.lavalink.dev/releases"
  pluginsDir: "./plugins"
  server:
    password: "stellarloomtemppass1test"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      http: false
      local: false
    filters: # All filters are enabled by default
      volume: false
      equalizer: false
      karaoke: false
      timescale: false
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false
    bufferDurationMs: 100 # GC 지연 감소를 위해 약간 낮춤.
    frameBufferDurationMs: 5000 # 5초로 줄여 메모리 사용량 감소.
    opusEncodingQuality: 5 # CPU 부하를 줄이고 대역폭을 최적화.
    resamplingQuality: LOW # 성능을 중점에 둔 설정.
    trackStuckThresholdMs: 15000 # 높은 안정성을 위해 증가.
    useSeekGhosting: false # Ghosting 비활성화로 불필요한 리소스 사용 방지.
    youtubePlaylistLoadLimit: 5 # 한 번에 적게 로드하도록 감소.
    playerUpdateInterval: 15 # 업데이트 주기를 늘려 트래픽 감소.
    youtubeSearchEnabled: true # 유튜브 검색 유지.
    soundcloudSearchEnabled: false # 대역폭 절약.

    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
    #youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
      #email: "" # Email of Google account
      #password: "" # Password of Google account
    #httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
      #proxyHost: "localhost" # Hostname of the proxy, (ip or domain)
      #proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
      #proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
      #proxyPassword: "" # Password for basic authentication

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30

plugins:
  youtube:
      enabled: true # Whether this source can be used.
      allowSearch: true # Whether "ytsearch:" and "ytmsearch:" can be used.
      allowDirectVideoIds: true # Whether just video IDs can match. If false, only complete URLs will be loaded.
      allowDirectPlaylistIds: true # Whether just playlist IDs can match. If false, only complete URLs will be loaded.
      # The clients to use for track loading. See below for a list of valid clients.
      # Clients are queried in the order they are given (so the first client is queried first and so on...)

      pot:
        token: "IjhCAUICJVvH0gFmMTMPMypxGGsYcCNHAzMjeChXKywzNwBrC0oBZghNF2kLRAVmA2YOZmcyBiRxRQ=="
        visitorData: "Cgs2M2hpZjZqaFA2ayjVi-q6BjIKCgJLUhIEGgAgLg%3D%3D"
      # clients:
      clients:
        - MUSIC
        - ANDROID_VR
        - WEB
        - WEBEMBEDDED
        # - TVHTML5EMBEDDED
        # - ANDROID_MUSIC
        # - ANDROID_TESTSUITE
        # - WEB
        # - WEBEMBEDDED
        # - MWEB
        # - ANDROID
        # - ANDROID_LITE
        # - MEDIA_CONNECT
        # - IOS

      # You can configure individual clients with the following.
      # Any options or clients left unspecified will use their default values
      # for those individual clients.
      # Client configurations will ONLY take effect if the client is registered above,
      # otherwise they are ignored.
      # ---------------- WARNING ----------------
      # This part of the config is for DEMONSTRATION PURPOSES ONLY!
      # Do NOT use this config before understanding what the options do.
      # You do NOT need to copy this config just because it is published here.
      # ---------------- WARNING ----------------
      clientOptions:
        WEB:
          # Example: Disabling a client's playback capabilities.
          playback: false
          videoLoading: false # Disables loading of videos for this client. A client may still be used for playback even if this is set to 'false'.
        WEBEMBEDDED:
          # Example: Configuring a client to exclusively be used for video loading and playback.
          playlistLoading: false # Disables loading of playlists and mixes.
          searching: false # Disables the ability to search for videos.
      
